In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("logistics_data.csv")

print(df)

   Client_ID Freight_Cost  Jan_Tonnage  Feb_Tonnage  Sensor_Temp
0       1001         4500        12000        13500         21.5
1       1002      missing         8500         9200         23.1
2       1003         3100        15000        16200         22.0
3       1001         2800         9000         9800         21.8
4       1004         1500        11000        11500         24.5


In [6]:
matrix = df[["Jan_Tonnage", "Feb_Tonnage"]].to_numpy()

print(matrix)

[[12000 13500]
 [ 8500  9200]
 [15000 16200]
 [ 9000  9800]
 [11000 11500]]


In [9]:
combined_weight = matrix[:, 0] + matrix[:, 1]

print("Combined Weight:")
print(combined_weight)

Combined Weight:
[25500 17700 31200 18800 22500]


In [10]:
processing_charge = matrix * 2

print("Processing Charge:")
print(processing_charge)

Processing Charge:
[[24000 27000]
 [17000 18400]
 [30000 32400]
 [18000 19600]
 [22000 23000]]


In [11]:
value = matrix[2, 1]

print("Value at Row 2, Column 1:")
print(value)

Value at Row 2, Column 1:
16200


In [12]:
df["Freight_Cost"] = df["Freight_Cost"].replace("missing", 0)

print(df)

   Client_ID Freight_Cost  Jan_Tonnage  Feb_Tonnage  Sensor_Temp
0       1001         4500        12000        13500         21.5
1       1002            0         8500         9200         23.1
2       1003         3100        15000        16200         22.0
3       1001         2800         9000         9800         21.8
4       1004         1500        11000        11500         24.5


In [13]:
df["Freight_Cost"] = df["Freight_Cost"].fillna(0)

print(df)

   Client_ID Freight_Cost  Jan_Tonnage  Feb_Tonnage  Sensor_Temp
0       1001         4500        12000        13500         21.5
1       1002            0         8500         9200         23.1
2       1003         3100        15000        16200         22.0
3       1001         2800         9000         9800         21.8
4       1004         1500        11000        11500         24.5


In [14]:
df["Freight_Cost"] = df["Freight_Cost"].astype(int)

print(df.dtypes)

Client_ID         int64
Freight_Cost      int32
Jan_Tonnage       int64
Feb_Tonnage       int64
Sensor_Temp     float64
dtype: object


In [15]:
mean_value = df["Freight_Cost"].mean()
median_value = df["Freight_Cost"].median()

print("Mean :", mean_value)
print("Median :", median_value)

Mean : 2380.0
Median : 2800.0
